### PR TITLE
[CN-232] Add simple Hazelcast Platform Operator guide

### PR DESCRIPTION
**Pull request by SeriyBg**

### CODE REVIEW

**Review by alparslanavci — CHANGES_REQUESTED** [review]
Thanks for the guide, @SeriyBg!

Added a few comments, also some more below:
- I think [antora.yaml](https://github.com/hazelcast-guides/hazelcast-platform-operator/blob/initial-guide/doc/antora.yml) should also be updated.
- It would be good if we can add integration tests.

**Review by mtyazici — CHANGES_REQUESTED** [review]
Left some comments about typos but other than that LGTM :+1:

**Review by mtyazici — APPROVED** [review]
Just added a comment about the yaml output of Hazelcast resource.

**Review by alparslanavci — APPROVED** [review]
Added a few comments, but overall looks good 👍

**Pull request merged**
